# Generated by Django 2.0.4 on 2019-11-24 16:27

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lawyer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buisness_address', models.CharField(max_length=100)),
                ('about', models.CharField(max_length=300, null=True)),
                ('contact', models.CharField(max_length=300, null=True)),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('phone_number', models.CharField(max_length=30)),
                ('liscence_number', models.IntegerField()),
                ('year_admitted', models.DateTimeField()),
                ('hcr_number', models.IntegerField(unique=True)),
                ('image', models.ImageField(null=True, upload_to='Pictures')),
                ('rate', models.IntegerField(default=5, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
